shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - semver@6.3.1
  - undici-types@6.21.0

packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  '@ringotangs/api-shapes': ^0.1.1
  dayjs: ^1.11.23
  zod: ^4.6.5

onlyBuiltDependencies:
  - esbuild
