/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../routes/__root'
import { Route as SplatRouteImport } from './../../routes/$'
import { Route as AppRouteImport } from './../../routes/_app'
import { Route as AppIndexRouteImport } from './../../routes/_app/index'
import { Route as AppAccountsRouteImport } from './../../routes/_app/accounts'
import { Route as AppAccountsIndexRouteImport } from './../../routes/_app/accounts.index'
import { Route as AppAccountsAccountRouteImport } from './../../routes/_app/accounts.$account'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsIndexRoute = AppAccountsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAccountsRoute,
} as any)
const AppAccountsAccountRoute = AppAccountsAccountRouteImport.update({
  id: '/$account',
  path: '/$account',
  getParentRoute: () => AppAccountsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/': typeof AppIndexRoute
  '/accounts': typeof AppAccountsRouteWithChildren
  '/accounts/$account': typeof AppAccountsAccountRoute
  '/accounts/': typeof AppAccountsIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/': typeof AppIndexRoute
  '/accounts/$account': typeof AppAccountsAccountRoute
  '/accounts': typeof AppAccountsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/accounts': typeof AppAccountsRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/accounts/$account': typeof AppAccountsAccountRoute
  '/_app/accounts/': typeof AppAccountsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/$' | '/' | '/accounts' | '/accounts/$account' | '/accounts/'
  fileRoutesByTo: FileRoutesByTo
  to: '/$' | '/' | '/accounts/$account' | '/accounts'
  id:
    | '__root__'
    | '/$'
    | '/_app'
    | '/_app/accounts'
    | '/_app/'
    | '/_app/accounts/$account'
    | '/_app/accounts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts': {
      id: '/_app/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts/': {
      id: '/_app/accounts/'
      path: '/'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AppAccountsIndexRouteImport
      parentRoute: typeof AppAccountsRoute
    }
    '/_app/accounts/$account': {
      id: '/_app/accounts/$account'
      path: '/$account'
      fullPath: '/accounts/$account'
      preLoaderRoute: typeof AppAccountsAccountRouteImport
      parentRoute: typeof AppAccountsRoute
    }
  }
}

interface AppAccountsRouteChildren {
  AppAccountsAccountRoute: typeof AppAccountsAccountRoute
  AppAccountsIndexRoute: typeof AppAccountsIndexRoute
}

const AppAccountsRouteChildren: AppAccountsRouteChildren = {
  AppAccountsAccountRoute: AppAccountsAccountRoute,
  AppAccountsIndexRoute: AppAccountsIndexRoute,
}

const AppAccountsRouteWithChildren = AppAccountsRoute._addFileChildren(
  AppAccountsRouteChildren,
)

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
